server:
  port: 8080
  servlet:
    context-path: /hme

spring:
  application:
    name: task-tracker


  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwertyk

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: debug